### ISSUE TITLE
Add custom tags, icons

### ISSUE THREAD

**Issue by GreenScreen410** [houtknots/BluemapTraincartsConnector#10]
There is only two types setting (connectorTag, connectorStorageTag). But I need more custom tags.
How about `...Tag`, `...TagIcon` prefix? It means if I make `expressBusTag`, then It matches `expressBusTagIcon`.

**Comment by houtknots** [comment]
That sounds like a great idea!

I was thinking on adding a configuration option to do this what do you think of this?
```yaml
custom_tags:
  expressBus: <iconurl>
  subway: <iconurl>
```
  
 If you have any other ideas please let me know, I will probably start working on it next week.

**Comment by GreenScreen410** [comment]
It's looking good, Thank you very much for creating this plugin.

**Comment by houtknots** [comment]
Hi @GreenScreen410,
I've just released version 1.20.6-v2. Please edit the config.yml file or delete it to allow for its recreation when the server starts.

If you encounter any issues or have suggestions, feel free to let me know! 😄

For the config.yml change, you have to delete the following:
```yaml
# A list of tags set to a Train which indicates whether the Train should be
# displayed on the BlueMap.
# Default: [bluemap, Bluemap, BlueMap]
connectorTags:
  - bluemap
  - Bluemap
  - BlueMap

connectorStorageTags:
  - bluemapstorage
  - Bluemapstorage
  - BlueMapStorage

# The Icon used by BlueMap to display the Trains with, found in the 
# "bluemap/web/assets/" directory
# Default: "assets/minecart-pio.png"
connectorTrainIcon: "assets/btc-minecart-pio.png"
connectorStorageTrainIcon: "assets/btc-storage-pio.png"
```

And change it to:
```yaml
# A list of tags set to a Train which indicates whether the Train should be
# displayed on the BlueMap.
# Make sure to put the icons files in the "bluemap/web/assets/" directory.
tagMap:
  bluemap: "assets/btc-minecart-pio.png"
  bluemapstorage: "assets/btc-storage-pio.png"

# The default icon for the TrainCart on the BlueMap
# Make sure to put the icons files in the "bluemap/web/assets/" directory.
# Default: "assets/btc-minecart-pio.png"
defaultTrainIcon: "assets/btc-minecart-pio.png"
```

The tags in the tagMap are case insensitive so both train tags bluemap or BLUEMAP will work.
